name: client
description: Client for provoking-parts

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  googleapis_auth: ^0.2.6

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
